### PR TITLE
replace ALLOW_FFTW with OFX_FFT_USE_FFTW & bufferSize fallback

### PR DESCRIPTION
**Pull request by danomatika**
Some updates after using ofxFft in a project:
- Having to comment a define in addon source code is icky (ALLOW_FFTW was defined in the last commit). I removed the #define line, renamed it to OFX_FFT_USE_FFTW, and added info on how to set it in Makefiles/IDEs.
- Logging a fatal error when the bufferSize is wrong didn't help much. Nicer to fallback to a correct size with a warning so at least everything works.
- I think 44100 is a better default samplerate across the board.

### CODE REVIEW

**Comment by danomatika** [comment]
I update this PR so it's up to date with master.

Also, I recommend removing the project files from the repo so the PG can do it's magic. As it stands now, the example projects all require manually installing the prebuilt fftw libs. I feel like the default state should use KISS so everything *just works*.

I can handle this in the PR if needed.

**Comment by danomatika** [comment]
still working, do not merge yet

**Comment by danomatika** [comment]
Ok, went ahead and removed the project files for ya. Tested on OS X wit the PG and everything works fine. I updated the readme on how to use the PG to create the example projects. I have a similar set up with all of my addons and that seems to work fine (ie. users are instructed to use the PG). This way, the project files don't go stale on us.

Also, ofxFft::create now prints a warning and falls back to creating ofxFftBasic when ofxFft is built without the OFX_FFT_USE_FFTW define is missing, so at least most things will still work without a crash. I added the define to the embedded linux builds in the addon_config.mk so that should *just work* as well.

**Comment by danomatika** [comment]
Ready to merge :)

**Comment by danomatika** [comment]
One more tiny commit which fixes a build error on Windows.

Please consider merging this PR as ofxFft does *not* work out of the box as it is and has been an issue with students.

**Comment by kylemcdonald** [comment]
thanks for all the work dan! it looks great to me, merging now. sorry for the delay.

**Comment by danomatika** [comment]
Great. Thanks!

**Pull request merged**
